name: "Deploy AWS CDK Chime Meeting Bot"

on:
  push:
    branches:
      - main
    paths:
      - "meet_ch.obs/**"  # Runs when any file changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region if different
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: |
          cd meet_ch.obs  # Ensure correct folder
          npm install

      - name: Synthesize CDK
        run: |
          cd meet_ch.obs
          cdk synth

      - name: Deploy CDK Stack
        run: |
          cd meet_ch.obs
          cdk deploy --require-approval never
